#!/bin/bash

BUILDCONFIG="~/.fed-artik-build.conf"
BUILDROOT=
BUILDARCH=armv7hl
HOSTS=/etc/hosts

. `dirname "$(readlink -f "$0")"`/fed-artik-common.inc

usage() {
	cat <<EOF
	usage: ${0##*/}

	-h              Print this help message
	-b [directory]	Specify bind mount directory
	-u [user]	Login to user
EOF
	exit 0
}

BUILDCONFIG="${BUILDCONFIG/#\~/$(eval echo ~$SUDO_USER)}"
parse_config $BUILDCONFIG

BUILDROOT="${BUILDROOT/#\~/$(eval echo ~$SUDO_USER)}"
eval BUILDROOT=$BUILDROOT
SCRATCH_ROOT=$BUILDROOT/BUILDROOT
LOCAL_REPO=$BUILDROOT/repos/$FEDORA_VER/$BUILDARCH/RPMS

sudo -H $SCRIPT_DIR/chroot_fedora $@ -H $HOSTS -b $LOCAL_REPO $SCRATCH_ROOT
