#!/bin/bash

BUILDCONFIG="/usr/local/share/fed-artik-tools/.fed-artik-build.conf"

. `dirname "$(readlink -f "$0")"`/fed-artik-common.inc

usage() {
	cat <<EOF
	usage: ${0##*/} [options]

	-h              Print this help message
	-B BUILDROOT	BUILDROOT directory, if not specified read from ~/FED-ARTIK-ROOT
	-C conf		Build configurations(If not specified, use default .fed-artik-build.conf
	-I ROOTFS	Import fedora rootfs
EOF
	exit 0
}

parse_options()
{
	for opt in "$@"
	do
		case "$opt" in
			-h|--help)
				usage
				shift ;;
			-B|--buildroot)
				BUILDROOT=`readlink -e "$2"`
				shift ;;
			-C)
				BUILDCONFIG="$2"
				shift ;;
			-I)
				IMPORT_ROOTFS="$2"
				shift ;;
			*)
				shift ;;
		esac
	done
}

make_initial_directories()
{
	local root_dir=$1

	install -d -o $user -g $user $root_dir
	install -d -o $user -g $user $root_dir/BUILDROOT
}

make_repository_directories()
{
	local root_dir=$1
	local repo_name=$2
	local repo_arch=$3

	install -d -o $user -g $user $root_dir/repos/
	install -d -o $user -g $user $root_dir/repos/$repo_name/
	install -d -o $user -g $user $root_dir/repos/$repo_name/$repo_arch/
	install -d -o $user -g $user $root_dir/repos/$repo_name/$repo_arch/{RPMS,SRPMS}
}

detect_fedora_version()
{
	local root_dir=$1
	local target_config=$2

	fedora_ver=`cat $root_dir/BUILDROOT/etc/fedora-release | awk '{ print $3 }'`

	if [ "$fedora_ver" != "$FEDORA_VER" ]; then
		sed -i "s/FEDORA_VER=.*/FEDORA_VER=$fedora_ver/" $target_config
		FEDORA_VER=$fedora_ver
	fi

	arch_str=`file $root_dir/BUILDROOT/bin/bash | grep aarch64`
	if [ "$arch_str" == "" ]; then
		buildarch=armv7hl
	else
		buildarch=aarch64
	fi

	if [ "$buildarch" != "$BUILDARCH" ]; then
		sed -i "s/BUILDARCH=.*/BUILDARCH=$buildarch/" $target_config
		BUILDARCH=$buildarch
	fi
}

if [ ! -e $BUILDCONFIG ]; then
	cat > $BUILDCONFIG << __EOF__
BUILDROOT=~/FED_ARTIK_ROOT
BUILDARCH=armv7hl
FEDORA_VER=f22
USE_DISTCC=0
USE_OFFICIAL_REPO=0
__EOF__
fi

parse_config $BUILDCONFIG
parse_options $@

BUILDROOT="${BUILDROOT/#\~/$(eval echo ~$SUDO_USER)}"
eval BUILDROOT=$BUILDROOT
SCRATCH_ROOT=$BUILDROOT/BUILDROOT

TARGET_CONFIG=$(eval echo ~$SUDO_USER)/.fed-artik-build.conf

install -m 644 -o $user -g $user $BUILDCONFIG $TARGET_CONFIG
make_initial_directories $BUILDROOT $FEDORA_VER $BUILDARCH

if [ "$IMPORT_ROOTFS" != "" ]; then
	sudo rm -rf $SCRATCH_ROOT/*
	sudo tar xf $IMPORT_ROOTFS -C $SCRATCH_ROOT
fi

detect_fedora_version $BUILDROOT $TARGET_CONFIG
make_repository_directories $BUILDROOT $FEDORA_VER $BUILDARCH

echo "Host setting is done"
echo "BUILDROOT -> " $BUILDROOT
echo "BUILDARCH -> " $BUILDARCH
echo "SCRATCH_ROOT -> " $SCRATCH_ROOT
echo "Local Repo -> " $BUILDROOT/repos/$FEDORA_VER/$BUILDARCH/RPMS
