#!/bin/bash

BUILDCONFIG=~/.fed-artik-build.conf
BUILDROOT=
BUILDARCH=armv7hl

. `dirname "$(readlink -f "$0")"`/fed-artik-common.inc

usage() {
	cat <<EOF
	usage: ${0##*/}

	-h              Print this help message
	-b [directory]	Specify bind mount directory
	-u [user]	Login to user
EOF
	exit 0
}

parse_config $BUILDCONFIG

eval BUILDROOT=$BUILDROOT
SCRATCH_ROOT=$BUILDROOT/BUILDROOT
LOCAL_REPO=$BUILDROOT/repos/$FEDORA_VER/$BUILDARCH/RPMS

sudo -H $SCRIPT_DIR/chroot_fedora $@ -b $LOCAL_REPO $SCRATCH_ROOT
